version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
     - "8088:80"
    volumes:
      - /Users/edwardmockridge/dev_deployment:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    networks:
     - laravel
    volumes:
     - /Users/edwardmockridge/Desktop:/docker-entrypoint-initdb.d

    environment:
      MYSQL_DATABASE: discussion_forum
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    tty: true
    ports: 
     - "3306:3306"
      

  php:
    image: php:8.2-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - /Users/edwardmockridge/dev_deployment:/var/www/html

    ports:
      - "9000:9000"
    networks:
      - laravel
